#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NB_CHARACTERS 128
#define NB_CHARACTERS_PSEUDO 20
#define RESPONSE_BUFFER_SIZE 10000

/* Code for the response */

#define NO_OTHER_USERS 100

#define PSEUDO_ACCEPTED 200
#define MESSAGE_GLOBAL_SEND 201
#define MESSAGE_PRIVATE_SEND 202
#define DISCONNECT_SUCCESS 203
#define HELP_SUCCESS 203

#define MESSAGE_GLOBAL_REDIRECT 300
#define MESSAGE_PRIVATE_REDIRECT 301

#define PSEUDO_ALREADY_USED 400
#define COMMAND_NOT_FOUND 401
#define GLOBAL_MESSAGE_ERROR 402
#define PRIVATE_MESSAGE_NOT_CORRESPONDING 403
#define PRIVATE_MESSAGE_USER_NOT_EXIST 404
#define DISCONNECT_NOT_CORRESPONDING 405
#define HELP_ERROR 406


#define RESPONSE_FROM_SERVER "Server"


/* Color for print */
#define BLUE "\x1B[34m"
#define GREEN "\x1B[32m"
#define YELLOW "\x1B[33m"
#define RED "\x1B[31m"
#define BOLD "\e[1m"
#define RESET "\x1B[0m"

#endif // CONSTANTS_H
